# =============================================================================
# Basic Application Configuration Example
# =============================================================================
# This is a simple, minimal configuration for getting started with the
# Spring AI Agent Platform. Perfect for development and learning.

spring:
  application:
    name: spring-ai-agent-platform
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      chat:
        options:
          model: gpt-4
          temperature: 0.7

server:
  port: 8080

logging:
  level:
    org.example: DEBUG
    org.springframework.ai: INFO

# Simple agent configurations
app:
  agents:
    # Basic conversational agent
    - name: chatAgent
      model: openai
      system-prompt: "You are a helpful and friendly assistant."
      workflow:
        type: graph
        chain:
          - nodeId: "response"
            prompt: "Respond to: {input}"

    # Simple task-oriented agent
    - name: taskAgent
      model: openai
      system-prompt: "You are a task-oriented assistant that helps with specific requests."
      workflow:
        type: graph
        chain:
          - nodeId: "analyze"
            prompt: "Analyze the task: {input}"
          - nodeId: "instructions"
            dependsOn: ["analyze"]
            prompt: "Provide step-by-step instructions to complete the task: {analyze}"

    # Basic routing agent using GraphWorkflow conditionals for different types of requests
    - name: routingAgent
      model: openai
      system-prompt: "You are a smart assistant that handles different types of requests."
      workflow:
        type: graph
        chain:
          - nodeId: "request_router"
            conditional:
              condition:
                type: CONTAINS
                field: "input"
                value: "question"
                ignoreCase: true
              thenStep:
                prompt: "Answer the question: {input}"
              elseStep:
                conditional:
                  condition:
                    type: CONTAINS
                    field: "input"
                    value: "task"
                    ignoreCase: true
                  thenStep:
                    prompt: "Help with the task: {input}"
                  elseStep:
                    prompt: "Provide general assistance for: {input}"