# Dynamic Route Discovery Examples
# This file demonstrates how the dynamic route discovery works with any route names
# The system will automatically discover routes from configuration without hardcoded values

spring:
  application:
    name: dynamic-routes-example
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:local-api-key}
      base-url: ${OPENAI_BASE_URL:http://localhost:1234/v1}

app:
  agents:
    # Example 1: Standard billing routes (existing functionality)
    - name: standardBillingAgent
      model: openai
      systemPrompt: "You are a billing specialist."
      workflow:
        type: graph
        chain:
          - nodeId: "billing_router"
            conditional:
              condition:
                type: CONTAINS
                field: "input"
                value: "invoice"
                ignoreCase: true
              thenStep:
                prompt: "Handle invoice request: {input}"
                tool: invoiceTool
              elseStep:
                conditional:
                  condition:
                    type: CONTAINS
                    field: "input"
                    value: "dispute"
                    ignoreCase: true
                  thenStep:
                    prompt: "Handle dispute request: {input}"
                    tool: disputeTool
                  elseStep:
                    conditional:
                      condition:
                        type: CONTAINS
                        field: "input"
                        value: "payment"
                        ignoreCase: true
                      thenStep:
                        prompt: "Handle payment request: {input}"
                        tool: paymentTool
                      elseStep:
                        prompt: "General billing assistance for: {input}"

    # Example 2: Custom route names (demonstrates dynamic discovery)
    - name: customRoutingAgent
      model: openai
      systemPrompt: "You are a custom routing agent with unique route names."
      workflow:
        type: graph
        chain:
          - nodeId: "custom_router"
            conditional:
              condition:
                type: CONTAINS
                field: "input"
                value: "customer service"
                ignoreCase: true
              thenStep:
                prompt: "Provide excellent customer service for: {input}"
                tool: customerServiceTool
              elseStep:
                conditional:
                  condition:
                    type: CONTAINS
                    field: "input"
                    value: "technical support"
                    ignoreCase: true
                  thenStep:
                    prompt: "Provide technical support for: {input}"
                    tool: techSupportTool
                  elseStep:
                    conditional:
                      condition:
                        type: CONTAINS
                        field: "input"
                        value: "sales"
                        ignoreCase: true
                      thenStep:
                        prompt: "Handle sales inquiry: {input}"
                        tool: salesTool
                      elseStep:
                        conditional:
                          condition:
                            type: CONTAINS
                            field: "input"
                            value: "product"
                            ignoreCase: true
                          thenStep:
                            prompt: "Provide product information for: {input}"
                          elseStep:
                            prompt: "Provide general assistance: {input}"

    # Example 3: E-commerce specific routes
    - name: ecommerceAgent
      model: openai
      systemPrompt: "You are an e-commerce specialist."
      workflow:
        type: graph
        chain:
          - nodeId: "ecommerce_router"
            conditional:
              condition:
                type: CONTAINS
                field: "input"
                value: "order"
                ignoreCase: true
              thenStep:
                prompt: "Track order status: {input}"
                tool: orderTrackingTool
              elseStep:
                conditional:
                  condition:
                    type: CONTAINS
                    field: "input"
                    value: "return"
                    ignoreCase: true
                  thenStep:
                    prompt: "Process return request: {input}"
                    tool: returnTool
                  elseStep:
                    conditional:
                      condition:
                        type: CONTAINS
                        field: "input"
                        value: "recommend"
                        ignoreCase: true
                      thenStep:
                        prompt: "Recommend products based on: {input}"
                        tool: recommendationTool
                      elseStep:
                        conditional:
                          condition:
                            type: CONTAINS
                            field: "input"
                            value: "inventory"
                            ignoreCase: true
                          thenStep:
                            prompt: "Check inventory for: {input}"
                            tool: inventoryTool
                          elseStep:
                            conditional:
                              condition:
                                type: CONTAINS
                                field: "input"
                                value: "shipping"
                                ignoreCase: true
                              thenStep:
                                prompt: "Provide shipping information: {input}"
                              elseStep:
                                prompt: "General e-commerce assistance for: {input}"

    # Example 4: Healthcare specific routes
    - name: healthcareAgent
      model: openai
      systemPrompt: "You are a healthcare information assistant."
      workflow:
        type: graph
        chain:
          - nodeId: "healthcare_router"
            conditional:
              condition:
                type: CONTAINS
                field: "input"
                value: "appointment"
                ignoreCase: true
              thenStep:
                prompt: "Help schedule appointment: {input}"
                tool: schedulingTool
              elseStep:
                conditional:
                  condition:
                    type: CONTAINS
                    field: "input"
                    value: "symptom"
                    ignoreCase: true
                  thenStep:
                    prompt: "Provide symptom information: {input}"
                    tool: symptomTool
                  elseStep:
                    conditional:
                      condition:
                        type: CONTAINS
                        field: "input"
                        value: "medication"
                        ignoreCase: true
                      thenStep:
                        prompt: "Provide medication information: {input}"
                        tool: medicationTool
                      elseStep:
                        conditional:
                          condition:
                            type: CONTAINS
                            field: "input"
                            value: "insurance"
                            ignoreCase: true
                          thenStep:
                            prompt: "Verify insurance coverage: {input}"
                            tool: insuranceTool
                          elseStep:
                            prompt: "General healthcare information assistance for: {input}"

    # Example 5: Mixed route types (some with tools, some without)
    - name: mixedRoutingAgent
      model: openai
      systemPrompt: "You handle various types of requests."
      workflow:
        type: graph
        chain:
          - nodeId: "mixed_router"
            conditional:
              condition:
                type: CONTAINS
                field: "input"
                value: "data"
                ignoreCase: true
              thenStep:
                prompt: "Analyze the data: {input}"
                tool: analyticsTool
              elseStep:
                conditional:
                  condition:
                    type: CONTAINS
                    field: "input"
                    value: "advice"
                    ignoreCase: true
                  thenStep:
                    prompt: "Provide general advice for: {input}"
                  elseStep:
                    conditional:
                      condition:
                        type: CONTAINS
                        field: "input"
                        value: "lookup"
                        ignoreCase: true
                      thenStep:
                        tool: lookupTool
                      elseStep:
                        conditional:
                          condition:
                            type: CONTAINS
                            field: "input"
                            value: "report"
                            ignoreCase: true
                          thenStep:
                            prompt: "Generate report for: {input}"
                            tool: reportTool
                          elseStep:
                            prompt: "General assistance for: {input}"

    # Example 6: International/Localized routes
    - name: internationalAgent
      model: openai
      systemPrompt: "You provide international support."
      workflow:
        type: graph
        chain:
          - nodeId: "international_router"
            conditional:
              condition:
                type: CONTAINS
                field: "input"
                value: "english"
                ignoreCase: true
              thenStep:
                prompt: "Provide English support: {input}"
                tool: englishSupportTool
              elseStep:
                conditional:
                  condition:
                    type: CONTAINS
                    field: "input"
                    value: "spanish"
                    ignoreCase: true
                  thenStep:
                    prompt: "Proporcionar soporte en español: {input}"
                    tool: spanishSupportTool
                  elseStep:
                    conditional:
                      condition:
                        type: CONTAINS
                        field: "input"
                        value: "french"
                        ignoreCase: true
                      thenStep:
                        prompt: "Fournir un support en français: {input}"
                        tool: frenchSupportTool
                      elseStep:
                        conditional:
                          condition:
                            type: CONTAINS
                            field: "input"
                            value: "currency"
                            ignoreCase: true
                          thenStep:
                            prompt: "Convert currency: {input}"
                            tool: currencyTool
                          elseStep:
                            conditional:
                              condition:
                                type: CONTAINS
                                field: "input"
                                value: "time"
                                ignoreCase: true
                              thenStep:
                                prompt: "Help with time zones: {input}"
                                tool: timeZoneTool
                              elseStep:
                                prompt: "General international support for: {input}"

    # Example 7: Complex nested route names
    - name: complexNamingAgent
      model: openai
      systemPrompt: "You handle complex routing scenarios."
      workflow:
        type: graph
        chain:
          - nodeId: "complex_router"
            conditional:
              condition:
                type: CONTAINS
                field: "input"
                value: "account"
                ignoreCase: true
              thenStep:
                prompt: "Manage user account: {input}"
                tool: accountTool
              elseStep:
                conditional:
                  condition:
                    type: CONTAINS
                    field: "input"
                    value: "api"
                    ignoreCase: true
                  thenStep:
                    prompt: "Handle API v2 integration: {input}"
                    tool: apiTool
                  elseStep:
                    conditional:
                      condition:
                        type: CONTAINS
                        field: "input"
                        value: "database"
                        ignoreCase: true
                      thenStep:
                        prompt: "Optimize database query: {input}"
                        tool: dbTool
                      elseStep:
                        conditional:
                          condition:
                            type: CONTAINS
                            field: "input"
                            value: "monitoring"
                            ignoreCase: true
                          thenStep:
                            prompt: "Monitor in real-time: {input}"
                            tool: monitoringTool
                          elseStep:
                            conditional:
                              condition:
                                type: CONTAINS
                                field: "input"
                                value: "machine learning"
                                ignoreCase: true
                              thenStep:
                                prompt: "Run ML inference: {input}"
                                tool: mlTool
                              elseStep:
                                prompt: "General complex system assistance for: {input}"

    # Example 8: Single route agent (edge case)
    - name: singleRouteAgent
      model: openai
      systemPrompt: "You handle one specific type of request."
      workflow:
        type: graph
        chain:
          - nodeId: "specialized_task"
            prompt: "Handle specialized task: {input}"
            tool: specializedTool

    # Example 9: Many routes agent (stress test)
    - name: manyRoutesAgent
      model: openai
      systemPrompt: "You handle many different types of requests."
      workflow:
        type: graph
        chain:
          - nodeId: "many_routes_router"
            conditional:
              condition:
                type: CONTAINS
                field: "input"
                value: "01"
                ignoreCase: true
              thenStep:
                prompt: "Handle route 01: {input}"
              elseStep:
                conditional:
                  condition:
                    type: CONTAINS
                    field: "input"
                    value: "02"
                    ignoreCase: true
                  thenStep:
                    prompt: "Handle route 02: {input}"
                  elseStep:
                    conditional:
                      condition:
                        type: CONTAINS
                        field: "input"
                        value: "03"
                        ignoreCase: true
                      thenStep:
                        prompt: "Handle route 03: {input}"
                      elseStep:
                        conditional:
                          condition:
                            type: CONTAINS
                            field: "input"
                            value: "04"
                            ignoreCase: true
                          thenStep:
                            prompt: "Handle route 04: {input}"
                          elseStep:
                            conditional:
                              condition:
                                type: CONTAINS
                                field: "input"
                                value: "05"
                                ignoreCase: true
                              thenStep:
                                prompt: "Handle route 05: {input}"
                              elseStep:
                                conditional:
                                  condition:
                                    type: CONTAINS
                                    field: "input"
                                    value: "06"
                                    ignoreCase: true
                                  thenStep:
                                    prompt: "Handle route 06: {input}"
                                  elseStep:
                                    conditional:
                                      condition:
                                        type: CONTAINS
                                        field: "input"
                                        value: "07"
                                        ignoreCase: true
                                      thenStep:
                                        prompt: "Handle route 07: {input}"
                                      elseStep:
                                        conditional:
                                          condition:
                                            type: CONTAINS
                                            field: "input"
                                            value: "08"
                                            ignoreCase: true
                                          thenStep:
                                            prompt: "Handle route 08: {input}"
                                          elseStep:
                                            conditional:
                                              condition:
                                                type: CONTAINS
                                                field: "input"
                                                value: "09"
                                                ignoreCase: true
                                              thenStep:
                                                prompt: "Handle route 09: {input}"
                                              elseStep:
                                                conditional:
                                                  condition:
                                                    type: CONTAINS
                                                    field: "input"
                                                    value: "10"
                                                    ignoreCase: true
                                                  thenStep:
                                                    prompt: "Handle route 10: {input}"
                                                  elseStep:
                                                    prompt: "General assistance for: {input}"