spring:
  application:
    name: spring-ai-agent-platform
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:local-api-key}
      base-url: ${OPENAI_BASE_URL:http://localhost:1234/v1}
      chat:
        options:
          model: ${OPENAI_MODEL:local-model}
          temperature: 0.7
    mcp:
      server:
        enabled: true
        timeout: 30s
        connection-timeout: 10s
        max-connections: 100
      client:
        enabled: true
        name: remoteToolsClient
        type: SYNC
        sse:
          connections:
            dataserver:
              url: http://dataserver.local:8080
              sse-endpoint: /mcp/sse
              message-endpoint: /mcp/message
        request-timeout: 30s

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.springai.agent: DEBUG
    org.springframework.ai: DEBUG

# Application-specific configuration
# Add your agents here or load them from external configuration
app:
  agents: []