spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4-turbo
          temperature: 0.3
    mcp:
      server:
        enabled: true
        base-url: /api/v2/agents/mcp
        sse-endpoint: /sse
        sse-message-endpoint: /message
      client:
        enabled: true
        name: productionToolsClient
        type: SYNC
        sse:
          connections:
            prodDataServer:
              url: https://prod-dataserver.company.com:8443
              sse-endpoint: /mcp/sse
              message-endpoint: /mcp/message
            analyticsServer:
              url: https://analytics.company.com:8443
              sse-endpoint: /mcp/sse
              message-endpoint: /mcp/message
        request-timeout: 60s

server:
  port: 8443
  ssl:
    enabled: true

logging:
  level:
    com.springai.agent: INFO
    org.springframework.ai: WARN
    root: WARN

app:
  agents:
    - name: enterpriseBillingAgent
      model: openai
      system-prompt: |
        You are an enterprise-grade billing specialist with advanced capabilities.
        Handle complex billing scenarios, enterprise contracts, and multi-currency transactions.
        Ensure compliance with international financial regulations.
      workflow:
        type: orchestrator
        orchestrator:
          manager-prompt: |
            You are a billing operations manager. Analyze the billing request: {input}
            Determine the appropriate workflow based on request complexity and compliance requirements.
          workers:
            - name: complianceWorker
              workflow:
                type: chain
                chain:
                  - "Review compliance requirements for: {input}"
                  - "Validate against current regulations and policies."
            - name: calculationWorker
              workflow:
                type: chain
                chain:
                  - "Perform detailed billing calculations for: {input}"
                  - "Apply appropriate taxes, discounts, and currency conversions."
            - name: auditWorker
              workflow:
                type: chain
                chain:
                  - "Audit the billing process for: {input}"
                  - "Generate audit trail and compliance documentation."
          synthesizer-prompt: |
            Based on manager decision: {managerDecision}
            And worker results: {workerResults}
            
            Generate a comprehensive billing response with full audit trail and compliance documentation.

    - name: productionAnalyticsAgent
      model: openai
      system-prompt: |
        You are a production-grade analytics agent optimized for enterprise data processing.
        Handle large-scale data analysis with focus on performance and accuracy.
      workflow:
        type: parallel
        parallel:
          tasks:
            - name: dataValidationTask
              workflow:
                type: chain
                chain:
                  - "Validate data integrity and quality for: {input}"
                  - "Identify and flag any data quality issues."
                  - "Generate data quality report."
            - name: performanceAnalysisTask
              workflow:
                type: chain
                chain:
                  - "Perform high-performance analysis on: {input}"
                  - "Generate statistical insights and performance metrics."
                  - "Create performance benchmarks and comparisons."
            - name: predictiveModelingTask
              workflow:
                type: chain
                chain:
                  - "Apply predictive modeling to: {input}"
                  - "Generate forecasts and trend predictions."
                  - "Validate model accuracy and confidence intervals."
          aggregator: |
            You are an enterprise analytics synthesizer. Combine all analysis results: {results}
            
            Create a comprehensive analytics report including:
            1. Executive Dashboard
            2. Data Quality Assessment
            3. Performance Analysis
            4. Predictive Insights
            5. Risk Assessment
            6. Actionable Recommendations

    - name: productionSupportAgent
      model: openai
      system-prompt: |
        You are a production support specialist handling critical system issues.
        Prioritize system stability and provide rapid incident resolution.
      workflow:
        type: routing
        routing:
          routes:
            critical:
              prompt: "Handle critical incident: {input}. Initiate emergency protocols and escalation procedures."
              tool: emergencyResponseTool
            performance:
              prompt: "Investigate performance issue: {input}. Analyze system metrics and identify bottlenecks."
              tool: performanceAnalysisTool
            maintenance:
              prompt: "Schedule maintenance for: {input}. Coordinate with stakeholders and minimize downtime."
              tool: maintenanceSchedulerTool
            monitoring:
              prompt: "Set up monitoring for: {input}. Configure alerts and thresholds."
              tool: monitoringConfigTool